// Generated by CoffeeScript 1.3.3
(function() {
  var Game, app, io, port;

  Game = function() {
    this.players = [];
    this.turn;
    this.president;
    return this.friend;
  };

  app = require('express').createServer(express.logger());

  port = process.env.PORT || 5000;

  io = require('socket.io').listen(app);

  app.listen(port);

  app.get('/', function(req, res) {
    return res.sendfile(__dirname + '/index.html');
  });

  io.sockets.on('connection', function(socket) {
    socket.on('publish', function(message) {
      return io.sockets.send(message);
    });
    socket.on('broadcast', function(message) {
      return socket.broadcast.send(message);
    });
    return socket.on('whisper', function(message) {
      return socket.emit('secret', message);
    });
  });

}).call(this);
